name: Python Workflow

on:
  push:
    branches:
      - Workflow
  schedule:
    - cron: '0 0 * * *'  # 设置每天 UTC 时间 00:00 触发

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: Workflow  # 指定分支为 Workflow
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
      
    - name: Set up configuration file
      run: |
        echo "[API_FETCH]" > config.ini
        echo "access_token = ${{ secrets.API_FETCH_ACCESS_TOKEN }}" >> config.ini
        echo "user_id = adachi9" >> config.ini
        echo "" >> config.ini
        echo "[API_ADD]" >> config.ini
        echo "access_token = ${{ secrets.API_ADD_ACCESS_TOKEN }}" >> config.ini
        
    - name: Run B2B.py script
      run: python B2B.py config.ini
